amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_25.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_26.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_27.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_28.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_29.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_30.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_31.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_32.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_33.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_34.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_35.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_36.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_37.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_38.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_39.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_40.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_41.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_42.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_43.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_44.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_45.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_46.yaml evolution_5000 -t NLX-NDv2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_47.yaml evolution_5000 -t NLX-NDv2
