amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_80.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_81.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_82.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_83.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_84.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_85.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_86.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_87.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_88.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_89.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_90.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_91.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_92.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_93.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_94.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_95.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_96.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_97.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_98.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_99.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
