amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_0.yaml heterogeneous -t  NLX-NDv2
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_1.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_2.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_3.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_4.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_5.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_6.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_7.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_8.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_9.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_10.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_11.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_12.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_13.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_14.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_15.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_16.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_17.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_18.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_19.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_20.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_21.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_22.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_23.yaml heterogeneous -t itpeastusv100cl
# amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_24.yaml heterogeneous -t itpeastusv100cl
