amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_40.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_41.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_42.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_43.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_44.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_45.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_46.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_47.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_48.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_49.yaml fear_stage_1_heterogeneous2 -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_50.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_51.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_52.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_53.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_54.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_55.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_56.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_57.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_58.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_59.yaml fear_stage_1_heterogeneous2 -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_60.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_61.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_62.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_63.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_64.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_65.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_66.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_67.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_68.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_69.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_70.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_71.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_72.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_73.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_74.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_75.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_76.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_77.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_78.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_79.yaml fear_stage_1_heterogeneous2 -t itpeastusv100cl2
