amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_0.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_1.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_2.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_3.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_4.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_5.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_6.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_7.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_8.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_9.yaml fear_baseline_heterogeneous_constLR -t itpseasiav100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_10.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_11.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_12.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_13.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_14.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_15.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_16.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_17.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_18.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_19.yaml fear_baseline_heterogeneous_constLR -t itpscusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_20.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_21.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_22.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_23.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_24.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_25.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_26.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_27.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_28.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_29.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_30.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_31.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_32.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_33.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_34.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_35.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_36.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_37.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_38.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
amlt run --yes archai/nlp/nvidia_transformer_xl/configs/nv_train_39.yaml fear_baseline_heterogeneous_constLR -t itpeastusv100cl2
