code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - sudo apt-get -y install git
  - pip install --user tensorboard
search:
  job_template:
    command:
    - set -e -o xtrace
    - bash scripts/apex_install.sh
    - pip install --user -e .
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}
    name: train_xl_VM_scale_2_thr_5M
    sku: G4
  max_trials: 2
  params:
  - name: config
    spec: discrete
    values:
    - dgx1_4gpu_fp32
  - name: n_layer
    spec: discrete
    values:
    - 5
  - name: n_head
    spec: discrete
    values:
    - 2,2,2,2,2
  - name: d_model
    spec: discrete
    values:
    - 256
  - name: d_embed
    spec: discrete
    values:
    - 256
  - name: div_val
    spec: discrete
    values:
    - 4
  - name: d_head
    spec: discrete
    values:
    - 128,128,128,128,128
  - name: d_inner
    spec: discrete
    values:
    - 1885,485,1335,1935,1835
  type: grid
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
