code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    20 --n_head 8,4,2,4,8,4,8,4,2,4,8,4,8,4,2,4,8,4,8,4 --d_model 128 --d_head 16,32,64,32,16,32,16,32,64,32,16,32,16,32,64,32,16,32,16,32                   --d_inner
    1152,1119,1991,1163,1652,1064,1152,1119,1991,1163,1652,1064,1152,1119,1991,1163,1652,1064,1152,1119
    --d_embed 256 --div_val 4 --experiment_name j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 8,4,2,4,8,4 --d_model 422 --d_head 16,32,64,32,16,32                   --d_inner
    1152,1119,1991,1163,1652,1064 --d_embed 256 --div_val 4 --experiment_name j1
  name: config_82_130
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
