code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,4,4,8,2,8 --d_model 512 --d_head 256,128,128,128,128,64,256,64                   --d_inner
    1570,1770,1520,1785,1720,1335,1070,1785 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,2,4,8,2,8,2,8 --d_model 256 --d_head 32,128,64,32,128,32,128,32                   --d_inner
    1635,1885,1835,1885,1735,1335,985,970 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j1
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,8,2,2,2,2 --d_model 256 --d_head 128,64,64,32,128,128,128,128                   --d_inner
    1570,1770,1835,1785,1735,1335,1785,970 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j2_pareto
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,2,4,4,2 --d_model 512 --d_head 256,128,256,128,128,256                   --d_inner
    1570,1770,1520,1920,1520,1720 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j3_pareto
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,2,4,2,2 --d_model 512 --d_head 256,128,256,128,256,256                   --d_inner
    1535,1770,1520,1785,1720,1720 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j4
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,4,4,4 --d_model 256 --d_head 128,64,64,64,64                   --d_inner
    1635,1770,1235,1785,1735 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j5
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,8,2,4,2,8 --d_model 512 --d_head 256,128,128,64,256,128,256,64                   --d_inner
    1635,1885,1835,1885,1120,1635,1785,1235 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j6
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,8,4,4,2,4,2 --d_model 512 --d_head 256,64,128,128,256,128,256                   --d_inner
    1735,1885,1520,1885,1120,1520,1670 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j7
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,2,4,4,2,2,2 --d_model 512 --d_head 256,128,256,128,128,256,256,256                   --d_inner
    1735,1620,1520,1785,1720,1335,1320,1720 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j8
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,2,2,4,2,2,2 --d_model 512 --d_head 256,128,256,256,128,256,256,256                   --d_inner
    1570,1985,1520,1785,1585,1720,1785,970 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j9
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,4,4,2 --d_model 512 --d_head 256,128,128,128,128,256                   --d_inner
    1735,1920,1520,1520,1185,1720 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j10
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,2,4,4,4,2,2 --d_model 512 --d_head 256,128,256,128,128,128,256,256                   --d_inner
    1735,1835,2035,1920,1720,1720,785,785 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j11
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,4,4,4,2,8 --d_model 512 --d_head 256,128,128,128,128,128,256,64                   --d_inner
    1635,1620,1520,1785,1520,1720,985,970 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j12
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,4,4,2,4,2,8,2 --d_model 256 --d_head 64,64,64,128,64,128,32,128                   --d_inner
    1735,1035,1520,585,1520,1720,1320,835 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j13
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,2,4,4,2,2,2 --d_model 512 --d_head 256,256,128,128,256,256,256                   --d_inner
    1370,1770,1570,1470,1170,1520,1320 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j14
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    3 --n_head 2,4,2 --d_model 512 --d_head 256,128,256                   --d_inner
    1920,1070,1935 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name j15
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,8,4,4,4,4,4,8 --d_model 256 --d_head 32,32,64,64,64,64,64,32                   --d_inner
    1735,1835,1520,885,1520,1720,1320,1720 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j16
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 4,2,4,2 --d_model 512 --d_head 128,256,128,256                   --d_inner
    1720,1770,1785,1785 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j17
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,8,4,4,2,2,2 --d_model 256 --d_head 32,32,64,64,128,128,128                   --d_inner
    1370,1770,1170,1785,1170,935,785 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j18
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 8,4,4,4,4,4 --d_model 512 --d_head 64,128,128,128,128,128                   --d_inner
    1320,1170,1785,1120,920,1520 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j19
  name: config_27
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
