code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
  setup:
  - set -e -o xtrace
  - sudo apt-get -y install git
  - pip install --user tensorboard
search:
  job_template:
    command:
    - set -e -o xtrace
    - bash scripts/apex_install.sh
    - pip install --user -e .
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 1111 --experiment_name config_2_seed_1111
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 1009 --experiment_name config_2_seed_1009
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 1200 --experiment_name config_2_seed_1200
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 1234 --experiment_name config_2_seed_1234
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 1302 --experiment_name config_2_seed_1302
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 1562 --experiment_name config_2_seed_1562
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 2222 --experiment_name config_2_seed_2222
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 3334 --experiment_name config_2_seed_3334
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 3425 --experiment_name config_2_seed_3425
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}                                         --max_step
      500 --seed 4567 --experiment_name config_2_seed_4567
    name: train_xl_config_2_500
    sku: G4
  max_trials: 8
  params:
  - name: config
    spec: discrete
    values:
    - dgx1_4gpu_fp32
  - name: n_layer
    spec: discrete
    values:
    - 7
  - name: n_head
    spec: discrete
    values:
    - 4
  - name: d_model
    spec: discrete
    values:
    - 64
  - name: d_embed
    spec: discrete
    values:
    - 256
  - name: div_val
    spec: discrete
    values:
    - 1
  - name: d_head
    spec: discrete
    values:
    - 16
  - name: d_inner
    spec: discrete
    values:
    - 1727
  type: grid
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
