code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,2,2,2,8,4,4,4 --d_model 256 --d_head 64,128,128,128,32,64,64,64                   --d_inner
    920,1935,1670,920,1820,1320,870,1185 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,2,2,2,8,2 --d_model 512 --d_head 128,256,256,256,64,256                   --d_inner
    920,1635,1670,1420,1670,1735 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j1
  name: config_119
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
