code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,8,2,4,8,4 --d_model 256 --d_head 128,64,64,32,128,64,32,64                   --d_inner
    1685,1085,1785,785,435,1935,1135,1135 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 4,2,8,4,2 --d_model 256 --d_head 64,128,32,64,128                   --d_inner
    1785,1620,1670,1585,1670 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j1_pareto
  name: config_171
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
