code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,8,8,4,8,4,4,2 --d_model 308 --d_head 32,16,16,32,16,32,32,64                   --d_inner
    1680,1761,1348,1535,1341,2014,1646,1096 --d_embed 128 --div_val 4 --experiment_name
    j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,8,8,4,8,4,4,2 --d_model 308 --d_head 32,16,16,32,16,32,32,64                   --d_inner
    1906,1998,1530,1742,1521,2285,1867,1244 --d_embed 128 --div_val 4 --experiment_name
    j1
  name: config_151_59
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
