code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,8,4,4,2,4,2,2 --d_model 512 --d_head 256,64,128,128,256,128,256,256                   --d_inner
    1570,1885,1785,1885,1120,1520,1785,1070 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,2,4,4,2,4,2 --d_model 512 --d_head 256,256,128,128,256,128,256                   --d_inner
    1635,1835,2035,1885,1520,1720,1670 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j1_pareto
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,8,4,4,2,4 --d_model 256 --d_head 128,32,64,64,128,64                   --d_inner
    1635,1870,1785,1070,1120,1520 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j2
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,2,8,2,8 --d_model 512 --d_head 256,256,256,64,256,64                   --d_inner
    1920,1920,1935,1285,1720,1970 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j3
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,8,2,4 --d_model 512 --d_head 256,128,128,64,256,128                   --d_inner
    1635,1920,1935,1285,1720,1970 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j4
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,4,8,2,4 --d_model 256 --d_head 128,128,64,32,128,64                   --d_inner
    1920,1920,2035,1920,1520,1970 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j5
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,2,8,2,2,4,2 --d_model 256 --d_head 128,64,128,32,128,128,64,128                   --d_inner
    1920,1920,1935,1285,1720,1970,1320,1720 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j6
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,2,2,4,2 --d_model 512 --d_head 256,256,256,128,256                   --d_inner
    1920,1920,1935,1520,1720 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j7
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,8,4,4,2,2 --d_model 256 --d_head 128,32,64,64,128,128                   --d_inner
    1635,1870,1785,1885,1120,1520 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j8
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,2,8,4,4 --d_model 512 --d_head 256,128,256,64,128,128                   --d_inner
    1735,1920,1520,1285,1970,1970 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j9
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,4,4,2 --d_model 256 --d_head 128,64,64,64,64,128                   --d_inner
    1820,1870,1520,1920,1520,1520 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j10
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,4,2,2,4,2 --d_model 512 --d_head 256,128,128,128,256,256,128,256                   --d_inner
    1635,1835,1785,1885,1120,1520,1670,1070 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j11
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,4,4,4,2,2,2 --d_model 256 --d_head 128,64,64,64,128,128,128                   --d_inner
    1635,1885,1785,1070,1120,1520,1670 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j12
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,8,4,4,2,4,2 --d_model 512 --d_head 256,64,128,128,256,128,256                   --d_inner
    1635,1885,1785,1885,1120,2035,1935 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j13
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,8,2,8,2,2 --d_model 256 --d_head 128,64,64,32,128,32,128,128                   --d_inner
    1570,1770,1935,1520,1735,970,1520,970 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j14
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,2,4,2,2,2,2 --d_model 256 --d_head 128,64,128,64,128,128,128,128                   --d_inner
    1920,1920,1935,1285,1720,970,1520,1135 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j15_pareto
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,8,4,4,2,2,2 --d_model 512 --d_head 256,64,128,128,256,256,256                   --d_inner
    1820,1885,1785,1070,1120,1520,1670 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j16
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,4,4,2,2,2 --d_model 256 --d_head 128,64,64,64,64,128,128,128                   --d_inner
    1920,1920,1520,1285,1720,2035,1320,1720 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j17
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,8,4,4,2,8,2,2 --d_model 512 --d_head 256,64,128,128,256,64,256,256                   --d_inner
    1735,1920,1785,1885,1120,1520,1935,1070 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j18
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 8,2,4,8,2 --d_model 512 --d_head 64,256,128,64,256                   --d_inner
    1570,1835,2035,1885,1520 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j19
  name: config_41
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
