code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
  setup:
  - set -e -o xtrace
  - sudo apt-get -y install git
  - pip install --user tensorboard
jobs:
- command: 'export CUDA_VISIBLE_DEVICES=0,1,2,3 &&                 python -m torch.distributed.launch
    --master_port=1234 --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py
    --config {config}                 --config_file wt103_base.yaml --n_layer 6 --n_head
    2,4,2,2,4,4 --d_model 128 --d_head 64,32,64,64,32,32                 --d_inner
    1229,1618,1901,952,1496,987 --d_embed 128 --div_val 4 --experiment_name job_0
    &

    export CUDA_VISIBLE_DEVICES=4,5,6,7 &&                 python -m torch.distributed.launch
    --master_port=2222 --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py
    --config {config}                 --config_file wt103_base.yaml --n_layer 12 --n_head
    2,4,2,2,4,4,2,4,2,2,4,4 --d_model 128 --d_head 64,32,64,64,32,32,64,32,64,64,32,32                 --d_inner
    1229,1618,1901,952,1496,987,1229,1618,1901,952,1496,987 --d_embed 128 --div_val
    4 --experiment_name job_1 &

    wait'
  name: train_xl_config_16
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
