code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - 'export CUDA_VISIBLE_DEVICES=0,1,2,3 &&                 python -m torch.distributed.launch
    --master_port=1234 --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_4gpu_fp32                 --config_file wt103_base.yaml --n_layer
    10 --n_head 8,2,4,4,8,4,8,8,2,4 --d_model 128 --d_head 16,64,32,32,16,32,16,16,64,32                 --d_inner
    897,2046,1216,632,701,950,1677,897,2046,1216 --d_embed 512 --div_val 4 --experiment_name
    job_0 &

    export CUDA_VISIBLE_DEVICES=4,5,6,7 &&                 python -m torch.distributed.launch
    --master_port=2222 --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_4gpu_fp32                 --config_file wt103_base.yaml --n_layer
    7 --n_head 8,2,4,4,8,4,8 --d_model 192 --d_head 16,64,32,32,16,32,16                 --d_inner
    897,2046,1216,632,701,950,1677 --d_embed 512 --div_val 4 --experiment_name job_1
    &

    wait'
  name: train_xl_config_config_188_0
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
