code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,4,8,2,2,4,4,2 --d_model 512 --d_head 64,128,64,256,256,128,128,256                   --d_inner
    1720,1720,1785,1120,1120,1935,1785,1420 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,2,4 --d_model 512 --d_head 256,128,256,128                   --d_inner
    920,1935,1785,920 --d_embed 512 --div_val 4 --max_step 500 --experiment_name j1
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,4,4,4 --d_model 512 --d_head 64,128,128,128                   --d_inner
    1970,1670,1785,1920 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j2
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,2,4,4,2,2,2 --d_model 256 --d_head 128,128,128,64,64,128,128,128                   --d_inner
    1285,1635,1220,1420,1420,1320,1020,1420 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j3
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,8,2,2,2 --d_model 256 --d_head 128,32,128,128,128                   --d_inner
    1620,1635,1335,1420,1770 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j4
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,4,8,2,2,2 --d_model 512 --d_head 256,128,128,128,64,256,256,256                   --d_inner
    1170,1670,1320,1920,1670,1570,1970,1120 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j5
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,8,2,2,2 --d_model 256 --d_head 128,32,128,128,128                   --d_inner
    1935,1635,1335,1420,1770 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j6
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,2,4,8,2,2,2 --d_model 512 --d_head 256,128,256,128,64,256,256,256                   --d_inner
    1970,1935,1770,1220,685,1270,1970,1185 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j7
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,8,2,2,2,4,2,4 --d_model 512 --d_head 256,64,256,256,256,128,256,128                   --d_inner
    1620,1635,1670,920,1770,1785,1785,1120 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j8
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,2,4 --d_model 512 --d_head 256,128,256,128                   --d_inner
    1620,1635,1220,1420 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j9
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,8,2,2,2,4,4,2 --d_model 256 --d_head 32,32,128,128,128,64,64,128                   --d_inner
    1620,1635,1335,1085,1770,1785,1785,1420 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j10
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,2,2,2,4,4,4 --d_model 256 --d_head 128,128,128,128,128,64,64,64                   --d_inner
    920,1635,1335,920,1770,1320,1785,1385 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j11
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,2,4,4,2,4,4 --d_model 256 --d_head 128,128,128,64,64,128,64,64                   --d_inner
    1285,1635,1785,1820,785,1935,1785,1835 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j12
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,2,2,4,4,4,2,4 --d_model 512 --d_head 128,256,256,128,128,128,256,128                   --d_inner
    920,1935,1785,920,1670,1320,1785,1120 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j13
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,8,4 --d_model 512 --d_head 256,128,64,128                   --d_inner
    1970,1720,1785,1570 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j14
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,2,2,4,8,2,4,2 --d_model 512 --d_head 64,256,256,128,64,256,128,256                   --d_inner
    1285,1670,1785,1920,785,1470,1785,1420 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j15
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,8,8,2,2,4,4,2 --d_model 512 --d_head 64,64,64,256,256,128,128,256                   --d_inner
    1720,1635,1785,1420,1770,1435,1785,1185 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j16
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,2,2,4,8,8,2,4 --d_model 512 --d_head 64,256,256,128,64,64,256,128                   --d_inner
    1685,1720,1785,1820,1820,1935,1370,1420 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j17
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,2,2,2,8,2,8 --d_model 256 --d_head 128,128,128,128,128,32,128,32                   --d_inner
    1685,1635,1335,1820,1770,1935,1370,1385 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j18
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,8,2,4,2,2,4,2 --d_model 256 --d_head 128,32,128,64,128,128,64,128                   --d_inner
    1285,1635,1335,1420,1420,1320,1020,1085 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j19
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,8,2,2 --d_model 512 --d_head 256,64,256,256                   --d_inner
    1935,1635,1220,1420 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j20
  name: config_72
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
