code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 4,4,2,4,4,4,2 --d_model 512 --d_head 128,128,256,128,128,128,256                   --d_inner
    1620,1635,1920,1420,785,1020,1370 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,2,8,2,4,2 --d_model 256 --d_head 128,64,64,128,32,128,64,128                   --d_inner
    1935,1935,1985,1085,1770,1785,1020,1385 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j1
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 8,4,4,4,8 --d_model 512 --d_head 64,128,128,128,64                   --d_inner
    1935,1635,1985,1785,1820 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j2
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,2,4,4 --d_model 512 --d_head 256,128,256,128,128                   --d_inner
    1685,1720,1570,1420,685 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j3
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 8,4,2,4,4 --d_model 512 --d_head 64,128,256,128,128                   --d_inner
    1685,1935,1920,1420,870 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j4
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,2,2,4,2,2 --d_model 512 --d_head 128,256,256,128,256,256                   --d_inner
    1770,1635,1220,1220,1320,1720 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j5
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,2,2,8,2,4,2 --d_model 256 --d_head 128,128,128,128,32,128,64,128                   --d_inner
    1620,1635,1670,1085,1770,1785,1170,1385 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j6
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 4,4,2,4 --d_model 512 --d_head 128,128,256,128                   --d_inner
    1770,1820,1220,1420 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j7
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 4,2,2,4,8,2,2 --d_model 256 --d_head 64,128,128,64,32,128,128                   --d_inner
    1620,1635,1670,1420,785,870,1170 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j8
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,2,2,2,2,8,4,8 --d_model 256 --d_head 32,128,128,128,128,32,64,32                   --d_inner
    1620,1635,1335,1085,1770,870,1785,1235 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j9
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 4,2,2,4,2,4,2 --d_model 256 --d_head 64,128,128,64,128,64,128                   --d_inner
    1620,1635,1820,1420,785,870,1020 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j10
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,2,2,2,2,2 --d_model 512 --d_head 128,256,256,256,256,256                   --d_inner
    1870,1635,1785,1420,1670,1720 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j11
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,8,2,2,8,2 --d_model 512 --d_head 256,64,256,256,64,256                   --d_inner
    1620,1635,1670,1420,1770,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j12
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,2,4,2,4 --d_model 256 --d_head 128,128,128,64,128,64                   --d_inner
    1670,1635,1785,1220,785,870 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j13
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 8,4,2,2,8,4 --d_model 512 --d_head 64,128,256,256,64,128                   --d_inner
    1620,1635,1820,1420,1670,1735 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j14
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 4,4,2,4,8 --d_model 512 --d_head 128,128,256,128,64                   --d_inner
    1935,1820,1985,1785,1320 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j15
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,4,4,4,4,8,4 --d_model 512 --d_head 64,128,128,128,128,64,128                   --d_inner
    1685,1520,1420,1520,1770,1720,1370 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j16
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,4,4,4,4,8,4 --d_model 512 --d_head 64,128,128,128,128,64,128                   --d_inner
    1670,1670,1320,1920,1620,1470,1270 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j17
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,4,2,2,2,4,2,4 --d_model 512 --d_head 128,128,256,256,256,128,256,128                   --d_inner
    920,1620,1720,920,870,1170,1570,970 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j18
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,4,8,4 --d_model 512 --d_head 64,128,64,128                   --d_inner
    1685,1935,1520,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j19
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 8,4,4,8,4 --d_model 512 --d_head 64,128,128,64,128                   --d_inner
    920,1720,1220,1120,1420 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j20
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,8,4,2 --d_model 512 --d_head 64,64,128,256                   --d_inner
    1685,1935,1785,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j21
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,8,2,4,2,2 --d_model 256 --d_head 64,32,128,64,128,128                   --d_inner
    920,1720,1335,1620,1370,1520 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j22
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 4,8,8,4,8 --d_model 256 --d_head 64,32,32,64,32                   --d_inner
    1785,1620,1670,1585,1670 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j23
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,8,2,4,8,4,2 --d_model 512 --d_head 256,128,64,256,128,64,128,256                   --d_inner
    1720,1435,1170,1420,1770,2035,2020,1185 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j24
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,4,4,8 --d_model 512 --d_head 64,128,128,64                   --d_inner
    1685,1935,1920,920 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j25
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,4,4,4 --d_model 512 --d_head 64,128,128,128                   --d_inner
    1685,1935,1620,1170 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j26
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,8,8 --d_model 512 --d_head 256,128,64,64                   --d_inner
    1685,1520,1785,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j27
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,4,4,4 --d_model 512 --d_head 64,128,128,128                   --d_inner
    1220,1935,1785,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j28
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,4,8,2,2,8,4,2 --d_model 256 --d_head 32,64,32,128,128,32,64,128                   --d_inner
    1135,485,1670,785,935,1785,935,1385 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j29
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,4,4,4 --d_model 512 --d_head 64,128,128,128                   --d_inner
    1120,1935,1970,1070 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j30
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,2,2,4 --d_model 512 --d_head 256,256,256,128                   --d_inner
    870,1070,1785,1220 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j31
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,4,2,2,8,4,2,4 --d_model 512 --d_head 128,128,256,256,64,128,256,128                   --d_inner
    1720,1620,1670,920,1670,1370,1570,1420 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j32
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,8,2,4,8,2,2 --d_model 512 --d_head 256,128,64,256,128,64,256,256                   --d_inner
    1620,1435,1170,1420,1770,1070,1885,970 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j33
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,2,4,4,2,2 --d_model 256 --d_head 64,128,64,64,128,128                   --d_inner
    920,1185,1335,1620,1535,1520 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j34
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,2,2,2,8,2,4 --d_model 512 --d_head 256,256,256,256,64,256,128                   --d_inner
    1620,1635,1670,1085,1770,1670,1670 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j35
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,4,4,4 --d_model 512 --d_head 64,128,128,128                   --d_inner
    1620,1435,1170,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j36
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 4,2,4,8,2 --d_model 512 --d_head 128,256,128,64,256                   --d_inner
    920,1620,1220,1120,1420 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j37
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 4,4,4,4,8,2,4 --d_model 512 --d_head 128,128,128,128,64,256,128                   --d_inner
    920,1620,1320,920,1670,1370,1270 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j38
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,2,4,8,2,4,2 --d_model 512 --d_head 256,256,256,128,64,256,128,256                   --d_inner
    1620,1935,1785,1085,1420,1785,1170,1385 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j39
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,2,2,4,8,2,4,2 --d_model 512 --d_head 64,256,256,128,64,256,128,256                   --d_inner
    1620,1670,1320,1085,1770,1470,1170,1120 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j40
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,4,4 --d_model 512 --d_head 256,128,128,128                   --d_inner
    1685,1935,1920,1220 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j41
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,4,4,4 --d_model 512 --d_head 64,128,128,128                   --d_inner
    1685,1935,1335,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j42
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,2,4,4 --d_model 512 --d_head 64,256,128,128                   --d_inner
    1685,1935,1785,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j43
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,4,4,4,8,2,4 --d_model 512 --d_head 64,128,128,128,64,256,128                   --d_inner
    1170,1935,1320,1920,685,1935,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j44
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,4,2,4,8,4 --d_model 512 --d_head 128,128,256,128,64,128                   --d_inner
    920,1620,1670,920,1670,1370 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j45
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,2,2,4,8,2,2 --d_model 512 --d_head 64,256,256,128,64,256,256                   --d_inner
    1685,1670,1320,1220,1170,1470,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j46
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 4,2,2,4,8 --d_model 256 --d_head 64,128,128,64,32                   --d_inner
    1620,1635,1670,1585,1770 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j47
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,2,4 --d_model 512 --d_head 256,128,256,128                   --d_inner
    1685,1935,1785,1220 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j48
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,2,4,8,2,4,2 --d_model 256 --d_head 128,128,128,64,32,128,64,128                   --d_inner
    1620,1935,1670,1785,685,1785,920,1385 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j49
  name: config_65
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
