code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,2,4,4,8,4,8 --d_model 128 --d_head 16,64,32,32,16,32,16                   --d_inner
    3640,7720,4773,2699,2944,3828,6410 --d_embed 512 --div_val 4 --experiment_name
    j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    25 --n_head 8,2,4,4,8,4,8,8,2,4,4,8,4,8,8,2,4,4,8,4,8,8,2,4,4 --d_model 128 --d_head
    16,64,32,32,16,32,16,16,64,32,32,16,32,16,16,64,32,32,16,32,16,16,64,32,32                   --d_inner
    897,2046,1216,632,701,950,1677,897,2046,1216,632,701,950,1677,897,2046,1216,632,701,950,1677,897,2046,1216,632
    --d_embed 512 --div_val 4 --experiment_name j1
  name: config_188_131
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
