code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,4,4,2,8 --d_model 512 --d_head 256,256,128,128,256,64                   --d_inner
    1820,1870,1785,1785,1970,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,2,4,4,2 --d_model 512 --d_head 256,256,128,128,256                   --d_inner
    1820,1870,1785,1520,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j1
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,4,4,4 --d_model 512 --d_head 256,128,128,128,128                   --d_inner
    1820,1870,1520,1470,1720 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j2
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 8,2,4,4,4,2 --d_model 256 --d_head 32,128,64,64,64,128                   --d_inner
    1635,1870,1785,1885,1735,1420 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j3
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,2,4,4 --d_model 512 --d_head 256,256,128,128                   --d_inner
    1735,1920,1935,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j4
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,4,4,4 --d_model 512 --d_head 256,128,128,128,128                   --d_inner
    1570,1870,1520,1470,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j5
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,4,4,2 --d_model 512 --d_head 256,128,128,128,256                   --d_inner
    1920,1870,1935,1470,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j6
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,2,4,4 --d_model 512 --d_head 256,128,256,128,128                   --d_inner
    1570,1870,1785,1470,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j7
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 8,2,2,4,4 --d_model 512 --d_head 64,256,256,128,128                   --d_inner
    1570,1885,1520,1885,1735 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j8
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,2,2,4,4 --d_model 512 --d_head 256,256,256,128,128                   --d_inner
    1570,1770,1520,1785,1170 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j9
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,4,4,4 --d_model 512 --d_head 256,128,128,128,128                   --d_inner
    1820,1870,1785,1470,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j10
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,2,4,2,2 --d_model 512 --d_head 256,256,128,256,256                   --d_inner
    1920,1885,1785,1885,1735 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j11
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,4,4,2 --d_model 512 --d_head 256,128,128,128,256                   --d_inner
    1920,1870,1785,1520,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j12
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,4,4,2,8 --d_model 256 --d_head 128,128,64,64,128,32                   --d_inner
    1635,1920,635,835,1385,1135 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j13
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,4,2,4 --d_model 256 --d_head 128,64,64,64,128,64                   --d_inner
    1235,1835,2035,1920,1520,1720 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j14
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,2,4,4,2,2,2 --d_model 256 --d_head 128,128,64,64,128,128,128                   --d_inner
    1735,1835,1785,535,1520,1720,1035 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j15
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,4,4,2,4 --d_model 256 --d_head 128,128,64,64,128,64                   --d_inner
    1635,1920,885,1585,1720,485 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j16
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,4,2,4,4,4 --d_model 256 --d_head 64,64,128,64,64,64                   --d_inner
    1735,685,2035,1920,835,1720 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j17
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,4,4,4,4 --d_model 256 --d_head 128,128,64,64,64,64                   --d_inner
    1635,1920,1785,835,2035,485 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j18
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,4,4,2,2,2,2 --d_model 256 --d_head 128,128,64,64,128,128,128,128                   --d_inner
    1835,1835,1785,1920,1385,2035,985,985 --d_embed 256 --div_val 4 --max_step 5000
    --experiment_name j19
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,8,2,4,4,4,2,2 --d_model 256 --d_head 32,32,128,64,64,64,128,128                   --d_inner
    1735,1835,2035,1920,1520,1735,1135,735 --d_embed 256 --div_val 4 --max_step 5000
    --experiment_name j20
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,8,2,4,2,2,4,4 --d_model 512 --d_head 256,64,256,128,256,256,128,128                   --d_inner
    1370,1870,1785,1470,1620,1520,1020,1570 --d_embed 512 --div_val 4 --max_step 5000
    --experiment_name j21
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,4,4,2 --d_model 512 --d_head 256,128,128,128,256                   --d_inner
    970,1420,1785,1370,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j22
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,2,4,4,4 --d_model 256 --d_head 128,64,128,64,64,64                   --d_inner
    1935,485,2035,1920,635,1720 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j23
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,2,4,2,2,4 --d_model 256 --d_head 64,128,64,128,128,64                   --d_inner
    1635,1920,1785,835,1720,1235 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j24
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,4,4 --d_model 512 --d_head 256,128,128,128                   --d_inner
    1735,870,2035,1920 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j25
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,4,4 --d_model 512 --d_head 256,128,128,128                   --d_inner
    1735,1870,2035,1320 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j26
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,2,2,4,2 --d_model 256 --d_head 128,128,128,64,128                   --d_inner
    1920,1770,1020,1520,685 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j27
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,4,4,2,2,2,8 --d_model 256 --d_head 128,64,64,128,128,128,32                   --d_inner
    1820,1585,1785,1470,1520,1520,1020 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j28
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,4,2,4 --d_model 256 --d_head 128,64,64,64,128,64                   --d_inner
    2035,1785,1785,835,1720,2035 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j29
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,4,2,4,8,2 --d_model 256 --d_head 128,64,64,64,128,64,32,128                   --d_inner
    1635,1920,1785,835,1720,485,1935,1135 --d_embed 256 --div_val 4 --max_step 5000
    --experiment_name j30
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,4,2,2,2,2 --d_model 512 --d_head 256,128,128,128,256,256,256,256                   --d_inner
    1570,1770,1785,1920,1520,1720,1035,585 --d_embed 512 --div_val 4 --max_step 5000
    --experiment_name j31
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,4,4,4 --d_model 512 --d_head 256,128,128,128,128                   --d_inner
    1735,1835,2035,1470,1170 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j32
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,4,4,2 --d_model 512 --d_head 256,128,128,128,128,256                   --d_inner
    1635,1920,1520,835,1720,485 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j33
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,2,4,2,4 --d_model 256 --d_head 128,64,128,64,128,64                   --d_inner
    1735,1835,1785,835,1720,1720 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j34
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,4,4,4,2,2,2,2 --d_model 256 --d_head 128,64,64,64,128,128,128,128                   --d_inner
    1735,1835,1520,1920,1520,1720,1320,785 --d_embed 256 --div_val 4 --max_step 5000
    --experiment_name j35_pareto
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,2,4,4 --d_model 256 --d_head 128,128,64,64                   --d_inner
    1735,1835,2035,1920 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j36
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,2,4,2,4,2,2 --d_model 256 --d_head 128,128,128,64,128,64,128,128                   --d_inner
    1635,1835,1785,835,1720,2035,1035,1135 --d_embed 256 --div_val 4 --max_step 5000
    --experiment_name j37
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,2,4,4,4 --d_model 256 --d_head 128,128,128,64,64,64                   --d_inner
    1635,1835,1785,1920,1520,1720 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j38
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,4,4,4 --d_model 256 --d_head 128,64,64,64,64,64                   --d_inner
    1735,1835,2035,1920,1520,1720 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j39
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,4,2,2 --d_model 512 --d_head 256,128,128,128,256,256                   --d_inner
    1635,1920,1785,1470,1720,1520 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j40
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,4,4 --d_model 512 --d_head 256,128,128,128                   --d_inner
    1570,1835,1520,1920 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name
    j41
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,4,4,2,2 --d_model 256 --d_head 128,128,64,64,128,128                   --d_inner
    1635,1920,1785,835,1720,485 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j42
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,2,4,4,2,2 --d_model 256 --d_head 128,128,64,64,128,128                   --d_inner
    1820,1920,1785,1470,1720,485 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j43
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,4,2,4 --d_model 256 --d_head 128,64,64,64,128,64                   --d_inner
    1635,1835,1785,1920,1520,485 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j44
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,2,4,2,8,2,2 --d_model 256 --d_head 128,128,128,64,128,32,128,128                   --d_inner
    1735,1770,1020,1920,1520,1335,1770,1870 --d_embed 256 --div_val 4 --max_step 5000
    --experiment_name j45
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,2,4,4,8 --d_model 256 --d_head 128,64,128,64,64,32                   --d_inner
    1735,1835,2035,1920,1170,1720 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j46
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,2,4,2 --d_model 256 --d_head 128,64,128,64,128                   --d_inner
    1635,1920,1785,835,1670 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j47
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,4,4,2,4 --d_model 256 --d_head 128,64,64,64,128,64                   --d_inner
    1635,1920,1785,1920,1720,1720 --d_embed 256 --div_val 4 --max_step 5000 --experiment_name
    j48
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    3 --n_head 2,4,2 --d_model 512 --d_head 256,128,256                   --d_inner
    1920,970,1935 --d_embed 512 --div_val 4 --max_step 5000 --experiment_name j49
  name: config_38
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
