code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 4,4,2,2,8,4,2 --d_model 256 --d_head 64,64,128,128,32,64,128                   --d_inner
    1735,1985,1835,1085,1585,1835,1785 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 4,4,4,2,2,4,2 --d_model 256 --d_head 64,64,64,128,128,64,128                   --d_inner
    1735,1285,1035,1935,935,835,1685 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j1
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,8,2,4,2,2 --d_model 256 --d_head 128,32,128,64,128,128                   --d_inner
    1685,1020,1170,1070,1120,1520 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j2
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,4,2 --d_model 512 --d_head 256,128,128,256                   --d_inner
    1920,1920,1520,1520 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j3
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,4,4,2,2,8,2 --d_model 512 --d_head 256,256,128,128,256,256,64,256                   --d_inner
    1920,1920,1520,1870,970,1570,870,1820 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j4
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 8,2,2,4,4 --d_model 512 --d_head 64,256,256,128,128                   --d_inner
    1720,2020,870,1170,2020 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j5
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,8,2,2,2,2,2,2 --d_model 256 --d_head 128,32,128,128,128,128,128,128                   --d_inner
    970,1485,1170,1070,1120,1520,1670,1685 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j6
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,4,4,8,2,4,2 --d_model 512 --d_head 64,128,128,64,256,128,256                   --d_inner
    1735,2020,870,1935,485,1635,1785 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j7
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,2,2,8 --d_model 512 --d_head 256,256,256,64                   --d_inner
    1870,1920,1420,1520 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j8
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,4,4,4,2,2,2,8 --d_model 512 --d_head 64,128,128,128,256,256,256,64                   --d_inner
    1635,1885,1785,1885,1735,970,685,1220 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j9
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,2,4,4,8 --d_model 512 --d_head 256,128,256,128,128,64                   --d_inner
    970,1020,1420,1070,1120,1270 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j10
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,8,4,4,2,2,2 --d_model 512 --d_head 64,64,128,128,256,256,256                   --d_inner
    1320,1885,870,1885,1570,970,685 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j11
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,2,4,8 --d_model 512 --d_head 256,256,128,64                   --d_inner
    1920,1020,1520,1520 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j12
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,8,2,4,2,8,2,8 --d_model 256 --d_head 32,32,128,64,128,32,128,32                   --d_inner
    1985,1585,535,1885,1535,2035,2035,1035 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j13
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,4,2,4,4,2,2 --d_model 512 --d_head 256,128,256,128,128,256,256                   --d_inner
    1320,1020,1170,1120,1120,970,1120 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j14_pareto
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,8,2,4,2,8 --d_model 512 --d_head 128,64,256,128,256,64                   --d_inner
    1635,1885,535,835,1120,1520 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j15
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 2,4,2,4,4,8 --d_model 512 --d_head 256,128,256,128,128,64                   --d_inner
    1870,1020,1170,1520,1270,1270 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j16
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,8,4,4,2,4,2 --d_model 256 --d_head 128,32,64,64,128,64,128                   --d_inner
    1635,1885,1785,1885,1120,1285,1670 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j17
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 4,4,2,4,4,2 --d_model 256 --d_head 64,64,128,64,64,128                   --d_inner
    1985,2020,535,1120,1570,970 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j18
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,4,8 --d_model 512 --d_head 256,128,128,64                   --d_inner
    1920,1920,1420,1520 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j19
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,8,2,4,4,4,2 --d_model 512 --d_head 64,64,256,128,128,128,256                   --d_inner
    1320,2020,1785,1120,1570,1285,1120 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j20
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,4,2,4,2,2,4 --d_model 512 --d_head 64,128,256,128,256,256,128                   --d_inner
    1320,1585,535,835,1535,970,2035 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j21
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,8,2,4,2,4,4,8 --d_model 256 --d_head 32,32,128,64,128,64,64,32                   --d_inner
    1985,1585,1785,1885,1735,2035,685,1635 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j22
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,8,4,4,2,4,2,8 --d_model 512 --d_head 64,64,128,128,256,128,256,64                   --d_inner
    1320,2020,1785,1120,1735,1285,685,1220 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j23
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,4,4,8,2,4,2,8 --d_model 256 --d_head 32,64,64,32,128,64,128,32                   --d_inner
    1635,1885,1835,1885,1735,1635,1785,1235 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j24
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,8,4,4,2,4,4 --d_model 512 --d_head 256,64,128,128,256,128,128                   --d_inner
    1635,1585,1785,835,1120,2035,2035 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j25
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,8,4,4,2,4,2 --d_model 512 --d_head 256,64,128,128,256,128,256                   --d_inner
    1320,2020,870,1120,1570,1520,1120 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j26
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,2,2,4,4,8,2,2 --d_model 512 --d_head 128,256,256,128,128,64,256,256                   --d_inner
    1720,1120,1020,1520,1520,1270,1320,1420 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j27
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 8,2,4,4 --d_model 512 --d_head 64,256,128,128                   --d_inner
    1720,1620,1020,1520 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j28
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,8,2,4,2,8,8,8 --d_model 512 --d_head 64,64,256,128,256,64,64,64                   --d_inner
    1985,1585,535,1885,1535,2035,1520,1035 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j29
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,8,2,4,4,8,8,8 --d_model 256 --d_head 64,32,128,64,64,32,32,32                   --d_inner
    1385,1585,885,1885,1535,2035,2035,1035 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j30
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 4,2,2,4 --d_model 512 --d_head 128,256,256,128                   --d_inner
    1420,1520,1070,1620 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j31_pareto
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,8,2,4,2,8,2,2 --d_model 512 --d_head 64,64,256,128,256,64,256,256                   --d_inner
    1985,1585,535,1885,870,2035,2035,1370 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j32
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,4,2,4,2,8,2,8 --d_model 256 --d_head 32,64,128,64,128,32,128,32                   --d_inner
    1135,1585,785,1885,1485,2035,2035,1035 --d_embed 256 --div_val 4 --max_step 500
    --experiment_name j33
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    3 --n_head 8,8,2 --d_model 512 --d_head 64,64,256                   --d_inner
    1635,1885,2020 --d_embed 512 --div_val 4 --max_step 500 --experiment_name j34
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 4,2,8,4 --d_model 512 --d_head 128,256,64,128                   --d_inner
    1070,1020,1020,1620 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j35
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,2,8,4,4,8,8,4 --d_model 512 --d_head 128,256,64,128,128,64,64,128                   --d_inner
    1720,1020,1020,1520,1520,1270,1320,1920 --d_embed 512 --div_val 4 --max_step 500
    --experiment_name j36
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    3 --n_head 2,4,2 --d_model 512 --d_head 256,128,256                   --d_inner
    1570,1770,1020 --d_embed 512 --div_val 4 --max_step 500 --experiment_name j37
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 4,8,4,4 --d_model 512 --d_head 128,64,128,128                   --d_inner
    1720,1820,1020,1520 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j38
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,4,2,4,8,4,2 --d_model 512 --d_head 256,128,256,128,64,128,256                   --d_inner
    920,1520,1070,1370,1170,1620,1770 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j39
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 4,4,4,4 --d_model 512 --d_head 128,128,128,128                   --d_inner
    1720,1370,1020,1520 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j40
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,2,4,8,8 --d_model 512 --d_head 256,256,128,64,64                   --d_inner
    1920,1920,1520,1520,970 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j41
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 4,4,4,4 --d_model 512 --d_head 128,128,128,128                   --d_inner
    1720,1620,1220,1520 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j42
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,8,8,4,2,8,2 --d_model 256 --d_head 32,32,32,64,128,32,128                   --d_inner
    1985,1535,535,1885,1535,2035,1885 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j43
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    6 --n_head 8,8,2,4,8,8 --d_model 256 --d_head 32,32,128,64,32,32                   --d_inner
    1985,1585,535,1885,1535,685 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j44
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,2,4,2 --d_model 256 --d_head 128,64,128,64,128                   --d_inner
    1570,1770,1020,1285,1720 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j45
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,4,4,4 --d_model 512 --d_head 256,128,128,128                   --d_inner
    1635,1885,1785,1885 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j46
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,2,4,4,2,4,2 --d_model 512 --d_head 256,256,128,128,256,128,256                   --d_inner
    1635,1020,1785,1520,1120,1270,1320 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j47
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,2,2,4 --d_model 512 --d_head 256,256,256,128                   --d_inner
    1570,1520,1020,1770 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j48
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    4 --n_head 2,8,2,4 --d_model 512 --d_head 256,64,256,128                   --d_inner
    1920,1720,1020,1770 --d_embed 512 --div_val 4 --max_step 500 --experiment_name
    j49
  name: config_2
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
