code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    9 --n_head 4,8,8,4,8,4,4,2,4 --d_model 384 --d_head 32,16,16,32,16,32,32,64,32                   --d_inner
    1482,1569,1129,1328,1121,1838,1446,860,1482 --d_embed 128 --div_val 4 --experiment_name
    j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    10 --n_head 4,8,8,4,8,4,4,2,4,8 --d_model 384 --d_head 32,16,16,32,16,32,32,64,32,16                   --d_inner
    1482,1569,1129,1328,1121,1838,1446,860,1482,1569 --d_embed 128 --div_val 4 --experiment_name
    j1
  name: config_151_24
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
