code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
  setup:
  - set -e -o xtrace
  - sudo apt-get -y install git
  - pip install --user tensorboard
search:
  job_template:
    command:
    - set -e -o xtrace
    - bash scripts/apex_install.sh
    - pip install --user -e .
    - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py                                         --config
      {config} --config_file wt103_base_FEAR.yaml                                         --n_layer
      {n_layer} --n_head {n_head} --d_model {d_model} --d_head {d_head}                                         --d_inner
      {d_inner} --d_embed {d_embed} --div_val {div_val}
    name: train_xl_config_188
    sku: G4
  max_trials: 2
  params:
  - name: config
    spec: discrete
    values:
    - dgx1_4gpu_fp32
  - name: n_layer
    spec: discrete
    values:
    - 7
  - name: n_head
    spec: discrete
    values:
    - 8,2,4,4,8,4,8
  - name: d_model
    spec: discrete
    values:
    - 128
  - name: d_embed
    spec: discrete
    values:
    - 512
  - name: div_val
    spec: discrete
    values:
    - 1
  - name: d_head
    spec: discrete
    values:
    - 16,64,32,32,16,32,16
  - name: d_inner
    spec: discrete
    values:
    - 897,2046,1216,632,701,950,1677
  type: grid
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
