code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,4,4,2,2,8,8 --d_model 256 --d_head 128,128,64,64,128,128,32,32                   --d_inner
    1920,1920,1520,1870,970,2035,870,1820 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 4,4,2,4,4,4,8 --d_model 512 --d_head 128,128,256,128,128,128,64                   --d_inner
    1220,1620,1620,1935,485,1520,1785 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j1
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,8,4,2 --d_model 512 --d_head 256,128,64,128,256                   --d_inner
    1770,1770,1520,1785,1970 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j2
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,2,4,2 --d_model 256 --d_head 128,64,128,64,128                   --d_inner
    1570,1770,1020,1685,1720 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j3
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 8,4,8,4,2 --d_model 512 --d_head 64,128,64,128,256                   --d_inner
    1570,1885,1285,1885,1735 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j4
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,4,8,4,2,8,2 --d_model 256 --d_head 128,64,32,64,128,32,128                   --d_inner
    1735,1835,1835,1435,1970,1585,1935 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j5
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 2,2,8,4,2,8,2,2 --d_model 512 --d_head 256,256,64,128,256,64,256,256                   --d_inner
    1570,1920,1520,1870,970,1335,870,970 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j6
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,4,4,2 --d_model 512 --d_head 256,128,128,128,256                   --d_inner
    1920,1920,1285,1870,970 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j7
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,4,4,4,4,4,2 --d_model 256 --d_head 128,64,64,64,64,64,128                   --d_inner
    1735,1835,1520,1920,1520,1720,1320 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j8
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 4,4,4,4,2 --d_model 512 --d_head 128,128,128,128,256                   --d_inner
    1920,1620,1520,1920,1970 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j9
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,4,8,4,4 --d_model 512 --d_head 256,128,64,128,128                   --d_inner
    1570,1770,1520,1920,1970 --d_embed 512 --div_val 4 --max_step 40000 --experiment_name
    j10
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 8,2,4,4,4,2,4,8 --d_model 512 --d_head 64,256,128,128,128,256,128,64                   --d_inner
    1635,1620,1520,1885,1735,1720,685,1720 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j11
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,4,2,4,2,2,8,2 --d_model 512 --d_head 128,128,256,128,256,256,64,256                   --d_inner
    1920,1620,1520,1920,1720,1720,1320,1720 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j12
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,4,8,4,2,4,2 --d_model 256 --d_head 128,64,32,64,128,64,128                   --d_inner
    1735,1285,1035,1935,485,1335,1785 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j13
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,4,4,8,2,2,8,2 --d_model 256 --d_head 64,64,64,32,128,128,32,128                   --d_inner
    1735,1920,1520,1870,970,1570,870,1235 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j14
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 4,4,4,4,4,2,2 --d_model 512 --d_head 128,128,128,128,128,256,256                   --d_inner
    1920,1620,1835,1920,1520,1720,1785 --d_embed 512 --div_val 4 --max_step 40000
    --experiment_name j15
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 2,4,2,4,2,4,2 --d_model 256 --d_head 128,64,128,64,128,64,128                   --d_inner
    1570,1770,1835,1435,1720,1335,1935 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j16
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 2,2,4,4,2 --d_model 256 --d_head 128,128,64,64,128                   --d_inner
    1635,1885,1785,1785,1735 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j17
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    5 --n_head 4,4,8,8,2 --d_model 256 --d_head 64,64,32,32,128                   --d_inner
    1735,1770,1835,1935,1970 --d_embed 256 --div_val 4 --max_step 40000 --experiment_name
    j18
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 4,4,4,8,2,4,2 --d_model 256 --d_head 64,64,64,32,128,64,128                   --d_inner
    1635,1285,1785,1935,1735,1635,1785 --d_embed 256 --div_val 4 --max_step 40000
    --experiment_name j19
  name: config_11
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
