code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    27 --n_head 8,2,8,2,8,2,2,8,2,8,2,8,2,2,8,2,8,2,8,2,2,8,2,8,2,8,2 --d_model 128
    --d_head 16,64,16,64,16,64,64,16,64,16,64,16,64,64,16,64,16,64,16,64,64,16,64,16,64,16,64                   --d_inner
    635,1880,1112,1226,1812,1517,1135,635,1880,1112,1226,1812,1517,1135,635,1880,1112,1226,1812,1517,1135,635,1880,1112,1226,1812,1517
    --d_embed 512 --div_val 4 --experiment_name j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,2,8,2,8,2,2 --d_model 500 --d_head 16,64,16,64,16,64,64                   --d_inner
    635,1880,1112,1226,1812,1517,1135 --d_embed 512 --div_val 4 --experiment_name
    j1
  name: config_83_133
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
