code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,8,2,2,4,2,8 --d_model 256 --d_head 32,32,128,128,64,128,32                   --d_inner
    1285,1635,1985,1785,1335,485,735 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j0
  - python -m torch.distributed.launch --nproc_per_node="8" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_8gpu_fp32                   --config_file wt103_base.yaml --n_layer
    7 --n_head 8,4,4,4,4,4,4 --d_model 256 --d_head 32,64,64,64,64,64,64                   --d_inner
    1435,1935,835,1320,685,1935,1785 --d_embed 256 --div_val 4 --max_step 500 --experiment_name
    j1
  name: config_50
  sku: G8
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
