code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  # image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04:latest
  registry: mcr.microsoft.com
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node=4 archai/nlp/nvidia_transformer_xl/train.py --config dgx1_4gpu_fp32 --config_file wt103_base_FEAR.yaml --n_layer 7 --n_head 2,4,2,2,4,8,4 --d_model 512 --d_inner 1576,1147,1624,1738,2029,1647,1049 --d_embed 256 --div_val 4
  name: config_164_2
  sku: G4
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
