code:
  local_dir: ./
data:
  remote_dir: dataroot
  storage_id: us_east
description: Train Transformer XL
environment:
  image: debadeepta/pytorch:1.7.0-cuda11.0-cudnn8-devel
  setup:
  - set -e -o xtrace
  - pip install --user tensorboard
jobs:
- command:
  - set -e -o xtrace
  - pip install --user -e .
  - python -m torch.distributed.launch --nproc_per_node="4" archai/nlp/nvidia_transformer_xl/train.py
    --config dgx1_4gpu_fp32                   --config_file wt103_base.yaml --n_layer
    8 --n_head 4,8,8,4,8,4,4,2 --d_model 128 --d_head 32,16,16,32,16,32,32,64                   --d_inner
    7840,8264,6121,7090,6082,9574,7665,4811 --d_embed 128 --div_val 4 --experiment_name
    job_0
  name: train_xl_config_config_151_14
  sku: G4
storage:
  us_east:
    container_name: phillytools
    storage_account_name: archaieast
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
